[2025-02-21T09:34:05.103+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-21T09:34:05.127+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-21T09:21:09.662952+00:00 [queued]>
[2025-02-21T09:34:05.140+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-21T09:21:09.662952+00:00 [queued]>
[2025-02-21T09:34:05.142+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 4
[2025-02-21T09:34:05.160+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): extract_task> on 2025-02-21 09:21:09.662952+00:00
[2025-02-21T09:34:05.165+0000] {standard_task_runner.py:72} INFO - Started process 2508 to run task
[2025-02-21T09:34:05.168+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', '***_v2_etl_dag', 'extract_task', 'manual__2025-02-21T09:21:09.662952+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/***_v2_etl_dag.py', '--cfg-path', '/tmp/tmprsg7x070']
[2025-02-21T09:34:05.175+0000] {standard_task_runner.py:105} INFO - Job 130: Subtask extract_task
[2025-02-21T09:34:05.194+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-21T09:34:05.237+0000] {task_command.py:467} INFO - Running <TaskInstance: finprode8_v2_etl_dag.extract_task manual__2025-02-21T09:21:09.662952+00:00 [running]> on host ***-airflow-scheduler
[2025-02-21T09:34:05.948+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ratih malini' AIRFLOW_CTX_DAG_ID='***_v2_etl_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T09:21:09.662952+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T09:21:09.662952+00:00'
[2025-02-21T09:34:05.951+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-21T09:34:05.983+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-02-21T09:34:05.986+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master yarn --packages org.postgresql:postgresql:42.2.18 --name arrow-spark --queue root.default /spark-scripts/***_v2_extract.py
[2025-02-21T09:34:07.353+0000] {spark_submit.py:641} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-02-21T09:34:07.355+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2025-02-21T09:34:07.357+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2025-02-21T09:34:07.360+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2025-02-21T09:34:07.362+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2025-02-21T09:34:07.363+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1029)
[2025-02-21T09:34:07.364+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1029)
[2025-02-21T09:34:07.365+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2025-02-21T09:34:07.367+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-02-21T09:34:07.368+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-02-21T09:34:07.369+0000] {spark_submit.py:641} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-02-21T09:34:07.392+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages org.postgresql:postgresql:42.2.18 --name arrow-spark --queue root.default /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-21T09:34:07.401+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=***_v2_etl_dag, task_id=extract_task, run_id=manual__2025-02-21T09:21:09.662952+00:00, execution_date=20250221T092109, start_date=20250221T093405, end_date=20250221T093407
[2025-02-21T09:34:07.434+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-21T09:34:07.436+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 130 for task extract_task (Cannot execute: spark-submit --master yarn --packages org.postgresql:postgresql:42.2.18 --name arrow-spark --queue root.default /spark-scripts/***_v2_extract.py. Error code is: 1.; 2508)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --packages org.postgresql:postgresql:42.2.18 --name arrow-spark --queue root.default /spark-scripts/***_v2_extract.py. Error code is: 1.
[2025-02-21T09:34:07.447+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-21T09:34:07.477+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-21T09:34:07.483+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
